steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/signalbridge', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/signalbridge']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'signalbridge', 
           '--image', 'gcr.io/$PROJECT_ID/signalbridge',
           '--platform', 'managed',
           '--region', 'us-east4',
           '--allow-unauthenticated']
