// pir_workflow.jsx - Simplified for Backend Workflow (Visualization Only)
import React from 'react';

/**
 * PIR Visualization Component - Displays backend-generated intelligence
 * No workflow logic needed - backend handles all intelligence generation
 */

/**
 * React component for PIR visualization
 */
const PIRVisualization = ({ decisionPoints, workflowData, styles }) => {
  if (!workflowData) {
    return (
      <div style={{ padding: '20px', backgroundColor: '#f8f9fa' }}>
        <h3 style={{ marginBottom: '20px', color: '#2d3748' }}>
          Priority Intelligence Requirements & Indicators
        </h3>
        <p>Loading AI-generated intelligence requirements...</p>
      </div>
    );
  }

  const { pirs, indicators } = workflowData;

  // Filter decision points to show only PIRs
  const pirDecisions = decisionPoints?.filter(d => d.type === 'PIR') || [];

  return (
    <div style={{ padding: '20px', backgroundColor: '#f8f9fa' }}>
      <h3 style={{ marginBottom: '20px', color: '#2d3748' }}>
        Priority Intelligence Requirements & Indicators
      </h3>
      
      {pirDecisions.length === 0 ? (
        <div style={{ 
          padding: '20px', 
          backgroundColor: 'white', 
          borderRadius: '8px',
          border: '1px solid #e2e8f0',
          textAlign: 'center',
          color: '#666'
        }}>
          No external intelligence requirements identified for this objective.
        </div>
      ) : (
        pirDecisions.map(decision => (
          <div key={decision.id} style={{ marginBottom: '30px' }}>
            <div style={{
              backgroundColor: '#4299e1',
              color: 'white',
              padding: '12px',
              borderRadius: '8px',
              marginBottom: '15px',
              fontWeight: '600'
            }}>
              Decision: {decision.title}
            </div>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
              {pirs[decision.id] && pirs[decision.id].map(pir => (
                <div key={pir.id} style={{
                  backgroundColor: 'white',
                  border: '1px solid #e2e8f0',
                  borderRadius: '6px',
                  padding: '15px'
                }}>
                  <div style={{
                    backgroundColor: '#48bb78',
                    color: 'white',
                    padding: '8px 12px',
                    borderRadius: '4px',
                    marginBottom: '10px',
                    fontSize: '14px',
                    fontWeight: '500'
                  }}>
                    PIR: {pir.question}
                  </div>
                  
                  <div style={{ paddingLeft: '20px' }}>
                    <div style={{ marginBottom: '8px', fontSize: '12px', color: '#666' }}>
                      Priority: {pir.priority} | Timeframe: {pir.timeframe}
                    </div>
                    
                    <div style={{ fontSize: '14px', fontWeight: '500', marginBottom: '8px' }}>
                      Collection Methods:
                    </div>
                    
                    {indicators[pir.id] && indicators[pir.id].map(indicator => (
                      <div key={indicator.id} style={{
                        backgroundColor: '#ffd89b',
                        padding: '8px',
                        borderRadius: '4px',
                        marginBottom: '5px',
                        fontSize: '12px'
                      }}>
                        <div style={{ fontWeight: '500' }}>{indicator.description}</div>
                        <div style={{ color: '#666', marginTop: '2px' }}>
                          Source: {indicator.source} | {indicator.frequency}
                        </div>
                      </div>
                    ))}
                    
                    {(!indicators[pir.id] || indicators[pir.id].length === 0) && (
                      <div style={{
                        backgroundColor: '#f7fafc',
                        padding: '8px',
                        borderRadius: '4px',
                        fontSize: '12px',
                        color: '#666',
                        fontStyle: 'italic'
                      }}>
                        Collection methods will be generated by the intelligence team
                      </div>
                    )}
                  </div>
                </div>
              ))}
              
              {(!pirs[decision.id] || pirs[decision.id].length === 0) && (
                <div style={{
                  backgroundColor: 'white',
                  border: '1px solid #e2e8f0',
                  borderRadius: '6px',
                  padding: '15px',
                  textAlign: 'center',
                  color: '#666',
                  fontStyle: 'italic'
                }}>
                  Intelligence requirements are being processed for this decision
                </div>
              )}
            </div>
          </div>
        ))
      )}
      
      {workflowData.summary && (
        <div style={{
          marginTop: '30px',
          padding: '15px',
          backgroundColor: '#edf2f7',
          borderRadius: '8px',
          fontSize: '14px'
        }}>
          <strong>Summary:</strong> {workflowData.summary.totalPIRs} intelligence requirements 
          across {workflowData.summary.totalDecisions} external decisions
        </div>
      )}
    </div>
  );
};

// Export only the visualization component - no workflow logic needed
export { PIRVisualization };
export default PIRVisualization;